version: '3.8'

services:
  web:
    build: .
    command: bundle exec hanami server --host=0.0.0.0
    ports:
      - 2300:2300
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db-volume:
  bundle:
